Update hardware information gathered by SUSEConnect
SUSE/doc-unversioned pull request #154
Opened 2024-07-11 13:21 UTC by mssola

As part of our last epic, we have introduced more parameters which are being gathered and sent to scc.suse.com. The public documentation should reflect these new parameters being sent.

2024-08-05 16:02 UTC, taroth21 commented
@mssola : Thanks for the PR (and sorry for not acting earlier, this probably got overlooked during the vacation period). @tbazant : Could you please take a look and review?

2024-08-06 07:37 UTC, tbazant requested changes
Just minor suggestions

2024-08-06 07:37 UTC, tbazant commented on suseconnect-visibility/xml/art_suseconnect_visibility.xml
> +            <entry>Depends on the architecture. It includes parameters such as devicetree information, virtualization type on PowerPC or System Z, among others</entry>
```suggestion
            <entry>Depends on the architecture. It includes parameters such as device-tree information or virtualization type on PowerPC or System Z.</entry>
```

2024-08-06 07:37 UTC, tbazant commented on suseconnect-visibility/xml/art_suseconnect_visibility.xml
> +              For each SAP installation: system_id (string) and instance_types (list of strings)
```suggestion
              <literal>system_id</literal> (string) and <literal>instance_types</literal> (list of strings) for each SAP installation.
```

2024-08-06 08:06 UTC, merged