SCC articles: add metadata
SUSE/doc-unversioned pull request #161
Opened 2024-08-05 16:39 UTC by taroth21

### PR creator: Description

Add metadata from 'Product Docs Metadata per deliverable' spreadsheet. 
Added a stub revhistory based on docserv-config logs.

### PR creator: Are there any relevant issues/feature requests?

Link to our [internal page](https://confluence.suse.com/display/documentation/Adding+metadata+to+all+SUSE+documentation).

2024-08-05 16:40 UTC, taroth21 commented on system-uptime-tracking/xml/art_system-uptime-tracking.xml
> +        <date>???</date>
@tbazant : This needs to be filled in whenever the article will be published on d.s.c (for now, it's only published as preview on sd.gh.io for our beta customers)

2024-08-06 07:30 UTC, tbazant requested changes
date updated

2024-08-06 07:30 UTC, tbazant commented on system-uptime-tracking/xml/art_system-uptime-tracking.xml
> +        <date>???</date>
```suggestion
        <date>2024-07-06</date>
```

2024-08-06 10:17 UTC, janajaeger approved these changes
LGTM

2024-08-06 11:29 UTC, merged