Improved explanation of facts-service-url parameter
SUSE/doc-unversioned pull request #181
Opened 2024-10-21 09:13 UTC by abravosuse

An Improved explanation of the right value of the facts-service-url parameter in the agent configuration file.

Once reviewed, this PR should be merged and published (no need to wait for new version release).

2024-10-30 08:50 UTC, dmpop commented on trento/xml/article_sap_trento.xml
> +            for communication with the checks engine (wanda). The right value of this parameter depends on
```suggestion
            for communication with the checks engine (wanda). The correct value of this parameter depends on
```

2024-10-30 08:50 UTC, dmpop commented on trento/xml/article_sap_trento.xml
> +             unless we have replaced trento_use and trento_user_password with custom values, in which case we should use them.
```suggestion
            <para> In a Kubernetes deployment, it is amqp://trento:trento@TRENTO_SERVER_HOSTNAME:5672/. If the default RabbitMQ username and password (trento) were updated using helm, 
            the parameter must use the custom value. </para>
            <para> In a systemd or containerized deployment, the correct value is amqp://trento_user:trento_user_password@TRENTO_SERVER_HOSTNAME:5672/vhost. If trento_use and trento_user_password were replaced with custom values, you can use them.
```

2024-11-04 10:22 UTC, tomschr requested changes
@abravosuse Minor markup suggestions

2024-11-04 10:22 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +            how Trento Server was deployed.</para>
```suggestion
            how &t.server; was deployed.</para>
```

2024-11-04 10:22 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +            <para> In a Kubernetes deployment, it is amqp://trento:trento@TRENTO_SERVER_HOSTNAME:5672/. If the default RabbitMQ username and password (trento) were updated using helm,
```suggestion
            <para> In a Kubernetes deployment, it is <uri>amqp://trento:trento@TRENTO_SERVER_HOSTNAME:5672/</uri>. If the default RabbitMQ username and password (trento) were updated using helm, 
```

2024-11-04 10:22 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +            <para> In a systemd or containerized deployment, the correct value is amqp://trento_user:trento_user_password@TRENTO_SERVER_HOSTNAME:5672/vhost. If trento_use and trento_user_password wer
Use upper case for placeholders:

```suggestion
            <para> In a systemd or containerized deployment, the correct value is <uri>amqp://TRENTO_USER:TRENTO_USER_PASSWORD@TRENTO_SERVER_HOSTNAME:5672/vhost</uri>. If <replaceable>TRENTO_USER</replaceable> and <replaceable>TRENTO_USER_PASSWORD</replaceable> were replaced with custom values, you can use them.
```

2024-11-04 10:55 UTC, abravosuse reviewed
LGTM @tomschr . Thank you! Ready to go!

2024-11-05 16:48 UTC, tomschr approved these changes

2024-11-05 16:48 UTC, merged