Changes in SUMA integration
SUSE/doc-unversioned pull request #186
Opened 2024-10-25 13:40 UTC by abravosuse

This PR must be reviewed but cannot be merged/published until the new version of Trento is out. It describes the second iteration of the integration of Trento with SUSE Manager, by which we can see the list of available patches and  upgradable packages for each registered host that is also managed by SUMA.

### PR creator: Description

Describe the overall goals of this pull request.

### PR creator: Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

2024-11-04 10:15 UTC, tomschr requested changes
@abravosuse Some small issues and a missing image. :slightly_smiling_face:

2024-11-04 10:15 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +              fileref="trento-upgradable-packages-overview.png" />
This image is missing according to the GitHub Action.

2024-11-04 10:15 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +   Onc the &suma; settings are configured, the &sap; administrator can test the connection
Typo:

```suggestion
   Once the &suma; settings are configured, the &sap; administrator can test the connection
```

2024-11-04 10:15 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +   by clicking the corresponding button.
What do you mean by "the corresponding button"? Is the button labeled "Test"? In that case, use:

```suggestion
   by clicking the <guimenu>Test</guimenu> button.
```

If you don't like that repeats "test" twice, you can use replace the verb "test" with "check".

2024-11-04 10:15 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +   If the connection is successful, the Host Details view of each host
```suggestion
   If the connection is successful, the <guimenu>Host Details</guimenu> view of each host
```

2024-11-04 10:15 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +    where the user can see the list of patches available for that particular host:</para>
```suggestion
   <para>Clicking on the <guimenu>Relevant Patches</guimenu> box takes us to the <guimenu>Relevant Patches</guimenu> overview,
    where the user can see the list of patches available for that particular host:</para>
```

2024-11-04 10:15 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +    where the user can see the list of packages that can be upgraded in that particular host:</para>
```suggestion
      <para>Clicking on the <guimenu>Upgradable Packages</guimenu> box takes us to the <guimenu>Upgradable Package</guimenu> overview,
    where the user can see the list of packages that can be upgraded in that particular host:</para>
```

2024-11-04 10:15 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +    vulnerabilities, or a list of affected hosts:</para>
Small rephrase and typo:

```suggestion
   <para>By clicking on an advisory or patch link, the user will access the corresponding details view. This view shows
   relevant information such as whether it requires a reboot or not, associated 
    vulnerabilities, or a list of affected hosts:</para>
```

2024-11-04 10:15 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +   enhancements. Security advisories are regarded as critical. If one is avaiable,
Missing Oxford comma. :wink: 

```suggestion
   <para>There are three types of patches or advisories: security advisories, bug fixes, and feature
   enhancements. Security advisories are regarded as critical. If one is avaiable,
```

2024-11-04 10:15 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +    is a security one, the health of the host will switch to warning. When a host cannot be found in
Typos:

```suggestion
   the health of the host will be set to critical. If there are available patches but none of them
    is a security one, the health of the host will switch to warning. When a host cannot be found in
```

2024-11-04 11:03 UTC, abravosuse reviewed
@tomschr missing file uploaded. All other suggestions accepted AS-IS. Thank you!

2024-11-06 08:49 UTC, abravosuse reviewed
LGTM!

2024-11-07 07:26 UTC, dmpop commented on trento/xml/article_sap_trento.xml
> +   of available patches and upgradable packages:</para>
```suggestion
   If the connection is successful, the <guimenu>Host Details</guimenu> view of each host
   managed by &suma; displays a summary
   of available patches and upgradable packages:</para>
```

2024-11-07 07:28 UTC, dmpop commented on trento/xml/article_sap_trento.xml
> +    where the user can see the list of patches available for that particular host:</para>
```suggestion
   <para>Click on <guimenu>Relevant Patches</guimenu> to open the <guimenu>Relevant Patches</guimenu> overview containing a list of patches available for that particular host:</para>
```

2024-11-07 07:30 UTC, dmpop commented on trento/xml/article_sap_trento.xml
> +    where the user can see the list of packages that can be upgraded in that particular host:</para>
```suggestion
      <para>Click <guimenu>Upgradable Packages</guimenu> to open the <guimenu>Upgradable Package</guimenu> overview containing a list of packages that can be upgraded on that particular host:</para>
```

2024-11-07 07:31 UTC, dmpop commented on trento/xml/article_sap_trento.xml
> +    vulnerabilities, or a list of affected hosts:</para>
```suggestion
   <para> Click  on an advisory or patch link to access the corresponding details view. This view shows
   relevant information, such as whether it requires a reboot, associated 
    vulnerabilities, or a list of affected hosts:</para>
```

2024-11-07 07:35 UTC, dmpop commented on trento/xml/article_sap_trento.xml
> +    &suma; or there is a problem retrieving the data for it, its health is set as unknnown.
```suggestion
   <para>There are three types of patches or advisories: security advisories, bug fixes, and feature
   enhancements. Security advisories are considered as critical. The health status of the host is set to critical if there is a security advisory. If there are patches available, but none of them
    is a security-related, the health status of the host switches to warning. When a host cannot be found in
    &suma;, or there is a problem retrieving the data for it, its health status is set as unknnown. 
```

2024-11-07 08:09 UTC, abravosuse reviewed
Thanks for the suggestions @dmpop . Just a small change request from my side: Upgradable Package > Upgradable Packages.

2024-11-07 08:09 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +    where the user can see the list of packages that can be upgraded in that particular host:</para>
```suggestion
      <para>Click <guimenu>Upgradable Packages</guimenu> to open the <guimenu>Upgradable Packages</guimenu> overview containing a list of packages that can be upgraded on that particular host:</para>>
```

2024-11-15 12:14 UTC, tomschr approved these changes

2024-11-26 13:46 UTC, tomschr approved these changes
Sounds good! :+1:

2024-12-06 09:41 UTC, merged