Rework Trento web console section
SUSE/doc-unversioned pull request #32
Opened 2022-11-08 18:05 UTC by tomschr

### PR creator: Description

### PR creator: Are there any relevant issues/feature requests?

https://confluence.suse.com/display/TRNT/2022-08-10+Trento+Documentation:

Split it in two sections:

1. Configuration: where we describe the different configuration options currently available in the console. Particularly:
   * cluster settings (we can reutilize the existing content)
   * tags on overviews (hosts, clusters, sap systems, HANA databases)
2. Use cases:
   * dashboard description (we can reutilize de exiting content)
   * what to do when host status is not green
   * what to do when pacemaker cluster status is not green
   * what to do when database status is not green
   * what to do wen SAP instances status is not green

2023-01-18 15:19 UTC, abravosuse requested changes

2023-01-18 15:19 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +      </para>
```suggestion
      <para>
       Tags are a means to label specific objects with a purpose, location, owner, or any other
       property you like. Such objects can be hosts, clusters, databases, or SAP systems.
       Tags make it easer to distinguish and show all these different objects, making
       your lists more readable and searchable. You can use any text you like to create
       your tags except blank spaces and special characters other than + - = . , _ : and @.
      </para>
```

2023-01-18 15:19 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +        </para>
```suggestion
        <para>
          The same principle applies to the other objects in Trento, be it <guimenu>Clusters</guimenu>,
          <guimenu>SAP Systems</guimenu>, or <guimenu>HANA Databases</guimenu>.
        </para>
```

2023-01-18 15:19 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +            </para>
```suggestion
<para>
In the Trento dashboard, go to the overview corresponding to the object for which you want to remove tags. For example, the <guimenu>Hosts</guimenu> overview.
</para>
```

2023-01-18 15:19 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +              In the <guimenu>Hosts</guimenu> view, search for your host you want to remove a tag.
```suggestion
              In the <guimenu>Hosts</guimenu> overview, search for the host you want to remove a tag from.
```

2023-01-18 15:19 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +          With tags, you can show only those parts you are interested in. For example, if
```suggestion
          With tags, you can show only those objects you are interested in. For example, if
```

2023-01-18 15:19 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +              In the Trento dashboard, click the respective part you are interested in.
```suggestion
              In the Trento dashboard, go to the respective overview you are interested in.
```

2023-01-18 15:19 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +              The pull down menu opens and shows you all of your definied tags.
```suggestion
              The pull down menu opens and shows you all of your defined tags.
```

2023-01-18 16:35 UTC, abravosuse requested changes

2023-01-18 16:35 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +              <imagedata width="70%" fileref="trento-web-pacemaker-cluster-details-view.png"/>
I accidentally marked the previous comment as resolved but the issue with the screenshot persists:

This screenshot has been take in a small screen. The checks result section should show on the left of the section with the cluster runtime information (provider, SID, fencing type, etc). Both sections should be horizontally aligned.

2023-01-18 16:35 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +      One of Trento's main feature is to provide checks for the HANA scale-up performance optimized two-node clustes in your SAP Landscape.
```suggestion
      One of Trento's main features is to provide checks for the HANA scale-up performance optimized two-node clustes in your SAP Landscape.
```

2023-01-18 16:35 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +      <step>
Still pending

2023-01-18 16:35 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +            <imagedata width="80%" fileref="trento-web-home.png" />
Still pending

2023-01-18 16:35 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +            </para>
```suggestion
            <para>
              It shows the number of systems with at lease one layer in critical (red) status.
            </para>
```

2023-01-18 16:35 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +          </step>
Still pending

2023-01-18 16:38 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +          </step>
Yes, I found out it's actually a problem in our stylesheets. I fixed it in PR openSUSE/suse-xsl#529.

2023-01-18 16:39 UTC, tomschr commented
I will look into the open issues tomorrow.

2023-01-19 12:30 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +            <imagedata width="80%" fileref="trento-web-home.png" />
I'm not entirely sure, so I did the screenshot again and committed it to commit ea60b89. Does that help?

2023-01-19 15:29 UTC, abravosuse requested changes

2023-01-19 15:29 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +            <imagedata width="80%" fileref="trento-web-home.png" />
Yes, it is fixed now.

2023-01-20 10:13 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +              <imagedata width="80%" fileref="trento-web-pacemaker-cluster-details-view.png"/>
Yes, please do!

2023-01-20 10:50 UTC, merged