Changes for version 2.1.0
SUSE/doc-unversioned pull request #84
Opened 2023-08-07 13:10 UTC by abravosuse

### PR creator: Description

Introducing changes for version 2.1.0

2023-08-07 13:19 UTC, abravosuse commented
@tomschr this PR is not to be merged until the new version is out.

2023-08-07 14:51 UTC, tomschr commented
@abravosuse Thanks Alberto! :+1: I haven't gone through it yet, but fixed a missing `</para>` tag in commit 4283531.

2023-08-09 13:41 UTC, tomschr requested changes
@abravosuse Thanks for the contribution! :+1: Have some ideas and suggestions.

2023-08-09 13:44 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +          &hana; clusters and ASCS/ERS clusters</para>
Yes, SAP customers should be familiar with what an ASCS/ERS cluster means.

2023-08-09 13:49 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +       For example, if the user cleans up the host where the Primary Application Server of an SAP System is deregistered,
The Primary Application Server is a unique name. That said, the sentence is wrong. It should say: "For example, if the user cleans up the host where the primary application server of an SAP System is registered," not "deregistered."

2023-08-16 06:31 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +      </step>
I applied variant 1 in commit 5ce67d9b79

2023-08-16 06:33 UTC, tomschr approved these changes

2023-08-16 06:35 UTC, merged