Abravosuse improvements installations updates
SUSE/doc-unversioned pull request #86
Opened 2023-08-08 11:05 UTC by abravosuse

### PR creator: Description

Revision on installation, update and uninstallation procedures.

2023-08-09 11:02 UTC, tomschr requested changes
@abravosuse Thanks for the addition. Much appreciated. :+1: I have some suggestions, hope they make sense.

2023-08-10 08:26 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +          <para>Connect Helm to the existing &k8s; cluster.</para>
We cannot be more specific here, it really depends on the customer setup.

2023-08-10 08:29 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +        The following procedure deploys &t.server; on a single-node K3s cluster. Such set up is not recommended for production purposes.
The recommended case is to have a person with K8s knowledge and have him/her deploy -manually- Trento Server components on an existing/new cluster in a production fashion.

2023-08-10 08:30 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +        <para> Monitor the creation and start-up of the Trento Server pods and wait until they are all in ready/running status:</para>
In this case it has to be ready AND running.

2023-08-10 08:31 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +          <para>Remember to add set the helm experimental flag if you are using a version of Helm lower than 3.8.0.
set

2023-08-10 08:33 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +        <para> Monitor the creation and start-up of the Trento Server pods and wait until they are all in ready/running status:</para>
Ok, replaced "or" with "and". It should work now and you can accept it.

2023-08-10 08:34 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +          <para>Remember to add set the helm experimental flag if you are using a version of Helm lower than 3.8.0.
```suggestion
          <para>Remember to set the helm experimental flag if you are using a version of Helm lower than 3.8.0.
```

2023-08-10 08:38 UTC, merged