New section of Trento version history
SUSE/doc-unversioned pull request #90
Opened 2023-08-16 10:29 UTC by tomschr

### PR creator: Description

A section describing the different versions available of Trento along with their most important user-facing features.

### Confluence

* https://confluence.suse.com/display/TRNT/2023-08-16+Trento+Documentation

2023-08-16 15:12 UTC, abravosuse reviewed
@tomschr I have added initial content to this section. Please review when you get a chance. Thanks!

2023-08-16 15:19 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +          <para>Addtion of VMware to the list of known platforms.</para>
Typo:

```suggestion
          <para>Addition of VMware to the list of known platforms.</para>
```

2023-08-16 15:20 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +          https://www.trento-project.io/web/swaggerui/ and https://www.trento-project.io/wanda/swaggerui/ respectiverly.</para>
Use links:

```suggestion
          <link xlink:href="https://www.trento-project.io/web/swaggerui/"/> and <link xlink:href="https://www.trento-project.io/wanda/swaggerui/"/> respectiverly.</para>
```

2023-08-16 15:22 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +       <para> Consisting of Helm chart 1.2.0, web 1.2.0, runner 1.1.0 and agent 1.1.0. Released on 2022/11/04.</para>
I think the version _and_ the release date are something the reader is interested in. As such, it should be more prominent and not hidden in a sentence:

```suggestion
       <term>Version 1.2.0, released on 2022/11/04</term>
       <para> Consisting of Helm chart 1.2.0, web 1.2.0, runner 1.1.0 and agent 1.1.0. </para>
```

2023-08-16 15:23 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +       <para> Consisting of Helm chart 1.1.0, web 1.1.0, runner 1.0.1 and agent 1.1.0. Released on 2022/07/14.</para>
```suggestion
        <term>Version 1.1.0, released on 2022/07/14</term>
       <para> Consisting of Helm chart 1.1.0, web 1.1.0, runner 1.0.1 and agent 1.1.0. </para>
```

2023-08-16 15:24 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +       <para> Consisting of Helm chart 1.0.0, web 1.0.0, runner 1.0.0 and agent 1.0.0. Released on 2022/04/29.</para>
```suggestion
       <term>Version 1.0.0 (general availability), released on 2022/04/29</term>
       <para> Consisting of Helm chart 1.0.0, web 1.0.0, runner 1.0.0 and agent 1.0.0. </para>
```

2023-08-16 15:29 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +       <para> Consisting of Helm chart 2.0.0, web 2.0.0, cchecks engine (wanda) 1.0.0 and agent 2.0.0. Released on 2023/04/26.</para>
```suggestion
        <term>Version 2.0.0, released on 2023/04/26</term>
       <para> Consisting of Helm chart 2.0.0, web 2.0.0, cchecks engine (wanda) 1.0.0 and agent 2.0.0.</para>
```

2023-08-16 15:32 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +           cost optimized, HANA scale-out) and other targes in the environment (hosts, HANA databases, NetWeaver instances), but also will allow customization of existing checks and
Entities:

```suggestion
           cost optimized, &hana; scale-out) and other targes in the environment (hosts, &hana; databases, &netweaver; instances), but also will allow customization of existing checks and
```

2023-08-16 15:36 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +           backend environment thanks to the event-driven technology behind it.</para>
* Basis -> basis? If it's not a unique name, use lowercase.
* Split the long sentence in two.

```suggestion
          <para>Clean, simple web console designed with SAP basis in mind. It reacts in real time to changes happening in the 
           backend environment thanks to the event-driven technology behind it.</para>
```

2023-08-16 15:37 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +          <para>Automated discovery of SAP systems, SAP instances and SAP HANA scale-up clusters.</para>
```suggestion
          <para>Automated discovery of SAP systems, SAP instances and &hana; scale-up clusters.</para>
```

2023-08-16 15:38 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +          <para>Configuration checks for HANA scale-up performance optimized two-node clusters on Azure, AWS and GCP.</para>
```suggestion
          <para>Configuration checks for &hana; scale-up performance optimized two-node clusters on Azure, AWS and GCP.</para>
```

2023-08-16 15:38 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +          <para>Basic integration with Grafana and Prometheus to provide graphic dashboards about CPU and Memory utilization in each discovered host.</para>
Typo:

```suggestion
          <para>Basic integration with Grafana and Prometheus to provide graphic dashboards about CPU and memory utilization in each discovered host.</para>
```

2023-08-16 16:58 UTC, abravosuse commented
Thanks for your suggestions @tomschr . I have reviewed and accepted them . I think it is ready to merge now.

2023-08-17 07:49 UTC, abravosuse requested changes

2023-08-17 07:49 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +        <para>For changes in the &t.server, web component, visit <link xlink:href="https://github.com/trento-project/web/releases"/>.</para>
```suggestion
        <para>For changes in the &t.server; web component, visit <link xlink:href="https://github.com/trento-project/web/releases"/>.</para>
```

2023-08-17 07:49 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +        <term>Version 2.1.0</term>
```suggestion
        <term>Version 2.1.0, released on 2023/08/02</term>
```

2023-08-17 07:49 UTC, abravosuse commented on trento/xml/article_sap_trento.xml
> +       <para> Consisting of Helm chart 2.1.0, web 2.1.0, checks engine (wanda) 1.1.0 and agent 2.1.0. Released on 2023/08/02.</para>
```suggestion
       <para> Consisting of Helm chart 2.1.0, web 2.1.0, checks engine (wanda) 1.1.0 and agent 2.1.0.</para>
```

2023-08-17 09:44 UTC, tomschr commented on trento/xml/article_sap_trento.xml
> +        <para>For changes in the &t.server, web component, visit <link xlink:href="https://github.com/trento-project/web/releases"/>.</para>
Is resolved now.

2023-08-17 09:45 UTC, tomschr commented
@abravosuse I've fixed some validation issues in the list (it can be tricky). :wink: See e55f9c5.

I can provide you with a PDF if you like, otherwise I can merge it if you like.

2023-08-17 10:55 UTC, abravosuse commented
@tomschr there is a change I made following your recommendation that is pending commit.

2023-08-17 11:45 UTC, tomschr commented
> there is a change I made following your recommendation that is pending commit.

I've already taken into account.

Here is the result (HTML):

<details>
  <summary>Screenshot of HTML</summary>

![Screenshot 2023-08-17 at 13-44-30 Getting started with Trento Premium](https://github.com/SUSE/doc-unversioned/assets/1312925/d58efb06-1fc7-442f-9699-6536bd8fb687)


</details>

2023-08-17 12:35 UTC, abravosuse requested changes
@tomschr please review this

2023-08-17 13:05 UTC, tomschr commented
@abravosuse Looks fine to me. :+1: Any objections to merge?

2023-08-17 13:50 UTC, merged